name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, arch: x86_64-linux }
          - { os: ubuntu-latest, arch: aarch64-linux }
    steps:
      - name: Build
        shell: bash
        run: |
          df -hT
          ls -alF /mnt
          pwd
          ls -alF
