name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, arch: x86_64-linux,  archname: x86_64 }
          - { os: ubuntu-latest, arch: aarch64-linux, archname: aarch64 }
    steps:
      - uses: actions/checkout@v2
      - name: Set up storage
        shell: bash
        run: |
          sudo mkdir -p /mnt/nix
          sudo mkdir /nix
          sudo mount --bind /mnt/nix /nix
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        if: matrix.job.arch == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3
      - name: Build
        shell: bash
        run: |
          nix --system ${{ matrix.job.arch }} bundle --bundler github:ralismark/nix-appimage/fc1192dbec82f5857f86ccc6dfdf2ad97bc9c62a .#jtts -o jtts-${{ matrix.job.archname }}.AppImage
          nix --system ${{ matrix.job.arch }} bundle --bundler github:ralismark/nix-appimage/fc1192dbec82f5857f86ccc6dfdf2ad97bc9c62a .#tts -o tts-${{ matrix.job.archname }}.AppImage
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            jtts-${{ matrix.job.archname }}.AppImage
            tts-${{ matrix.job.archname }}.AppImage
      - name: Clean up
        if: matrix.job.arch == 'x86_64-linux'
        shell: bash
        run: |
          for name in jtts tts; do
            file=$name-${{ matrix.job.archname }}.AppImage
            path=$(readlink -f $file)
            rm $file
            nix store delete $path
          done
      - name: Build with CUDA
        if: matrix.job.arch == 'x86_64-linux'
        shell: bash
        run: |
          nix --system ${{ matrix.job.arch }} bundle --bundler github:ralismark/nix-appimage/fc1192dbec82f5857f86ccc6dfdf2ad97bc9c62a .#tts-cuda -o tts-cuda.AppImage
      - name: Split CUDA artifacts
        if: matrix.job.arch == 'x86_64-linux'
        shell: bash
        run: |
          if [ "$(stat -L -c %s tts-cuda.AppImage)" -gt $((2000*1024*1024)) ]; then
            split -b 2000M -a 3 -d tts-cuda.AppImage tts-cuda.AppImage.
            rm tts-cuda.AppImage
          fi
      - name: Release CUDA artifacts
        if: matrix.job.arch == 'x86_64-linux'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            tts-cuda.AppImage*
